### ISSUE TITLE
HDR info

### ISSUE THREAD

**Issue by foXaCe** [Revan654/staxrip#1]
thank for your job.

 it possible to add auto Max CLL, MAX FALL and Master-Display info like x265 codec ?

**Comment by Revan654** [comment]
Max-CLL and MAX-FALL can be added easily.  However Master-Display is Tricky, Since allot of times the Master-Display settings is not known. Right now it just reads The single line, Which reads BT.2020. It needs all the data to import the data. If the actual coordinates are displayed it will import correctly.

Everything is Tested using MediaInfo 18.05. There been many Changes to HDR data and how it reads it.  The old version of Mediainfo displays things differently.

**Comment by Revan654** [comment]
Some of the code looks off, I need to take a closer look at this and try to figure out the formula. It seems the White Point is creating the issue.

**Comment by Revan654** [comment]
After looking through Mediainfo. There two options:.

1. It it reads BT.2020 + MaxCLL/MaxFALL and loads max Fall and CLL normally. With Master-Display I can alter the code and it will just use ther default Rec.2020. Since Mediainfo does not do the coordinates anymore.
2. Just have it load Max-CLL and Max-Fall and leave Master-Display alone. Which will require you to add in that data.

**Comment by Revan654** [comment]
Code has been altered, Will be seen in the next Release.
