### ISSUE TITLE
DCTFilter missing a dll file

### ISSUE THREAD

**Issue by crystaltech** [Revan654/staxrip#13]
**Describe the bug or Issue**
Getting a python exception: failed to load apps\plugins\vs\DCTFilter\DCTFilter.dll. GetLastError() returned 126.

needs the dll named libfftw3f-3.dll found here: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-DCTFilter/releases/download/r2/DCTFilter-r2.7z

**Comment by Revan654** [comment]
FFTW dll files has to be in the Search Path, Which is why your getting an Error. Windows should copy the files to System32 folder if you have proper admin rights & Windows didn't hijack your folder rights. If they were not copied due to Windows blocking the process. Then you need to copy the files to Windows\System32. 

Those files are already included with StaxRip Located at: StaxRip\Apps\FFTW

Also Make sure your App Manager is pointing to files.

**Comment by crystaltech** [comment]
on a fresh install of 1.9.0.0 on a different pc (windows 10) i was getting the same error as above. I did find the FFTW install button and it fixed it by installing to windows/system32. could this be added to first run if vapoursynth is detected as installed? if files are missing from windows/system32?

**Comment by Revan654** [comment]
I could try unlocking the directory and see if it would work without it being in System32 Directory. It might have been locked in the first place due to how python/VS reads & follows a path.

Most of the code is set to avisynth filters. I believe FFTW is set to FFT3DFilter and it can only have one setup action. 

With read & write access being what it is with system32 folder. It might be difficult to scan that folder. MS keeps adding more and more annoying security features. There even security locks on powershell now. Which blocks programs from read or executing functions.

I have no idea without testing it.

**Comment by crystaltech** [comment]
without installing it to system32, i copied that 1 dll file (libfftw3f-3.dll) to the DCTFilter folder and it fixed it as well it seems that only DCTFilter uses it. at least for vapoursynth. all in all its a wonderful job with the release and I do thank you for your time and effort with continuing this project.

**Comment by Revan654** [comment]
with it next to the DCTFilter it would now be in the search Path.

There are others that use FFTW.

VapourSynth is a giant PIA to deal with half the time.

**Comment by Revan654** [comment]
Resolved.
