### ISSUE TITLE
Encoding not possible without HDRColor

### ISSUE THREAD

**Issue by kjadfksjd** [Revan654/staxrip#2]
Hello,
I don't have this plugin and I can't use staxrip because of this.
Isn't there some type of fallback if this plugin is not installed?

Whatever I do I will get this message in return:
![staxrip_2018-06-11_05-26-47](https://user-images.githubusercontent.com/26279994/41211579-d2e96c26-6d27-11e8-845d-48b7b46d319e.png)

Any workaround?

**Comment by Revan654** [comment]
I have it coded that it's not required.

".IsRequired = False,"

If you can post your script and best of your ability what's happening. Worse case scenario I'll just delete the code for HDRColor for the public version. It shouldn't be asking your for it.

Also delete HDRColor line from the version Text file in the app folder and see if that makes any difference. Along with deleting all the settings. Try a fresh load to see if it makes any difference. I know when I removed it it didn't ask me for it.

**Comment by kjadfksjd** [comment]
Hello, see this example video please:
https://www.youtube.com/watch?v=g10agyZEPRk

I downloaded the release zip file -> unzip -> open -> save settings in same folder -> add file -> click next -> get HDRColor missing window.

**Comment by kjadfksjd** [comment]
I tried to delete & rename ffms2.avsi but I get the the window aksing for FFMS2 plugin.
I will wait for a new release build.

**Comment by proper88** [comment]
Same here, encoding not possible even when i delete the FFMS2.avsi.
Still waiting for the next release  ...
(Hope this will be very soon)

**Comment by Revan654** [comment]
It Strange, I did many test with it last night with it deleted. It never asked for the script. It's coded to optional. Make sure your using Fresh settings. You can use L-Smash or such until the next version is uploaded. Shouldn't be to long.

The code has already been changed on the site, The next release will be compiled soon. Since I have to change how the program reads HDR data since Mediainfo has changed how it displays the data.

**Comment by Revan654** [comment]
New Release is Up and it's been fixed.
