### ISSUE TITLE
 creates a fake HDR video

### ISSUE THREAD

**Issue by ABDOELSHEMY** [Revan654/staxrip#25]
hi @Revan654 
thank you for your great work on staxrip
i see this https://github.com/stax76/staxrip/issues/412 
could you please explain to me how to use this script to creates a fake HDR video, i google about it but did not found any information for that

**Comment by Revan654** [comment]
You can create the Metadata used for HDR(Minus Dolby Vision For obvious reasons). Without altering Coloring & lighting it will playback be exactly like SDR video.

To Create HDR like video, You have to play around with Matrix, Transfer and ColorPrime along with filters like AutoAdjust or use 3Dlut to try to re-produce HDR like color(BT709 to BT 2020/ST.2084).

Without a proper HDR monitor for grading the lighting may be a bit dim.

If you go with 3DLuts, Blackmagic Software includes a bunch of pre-made 3Dluts, You can install the App grab the Luts and then uninstall the software(Since Only the Paid version has HDR support). Only the .cube work, the only are designed for Blackmagic software.

Link: [https://www.blackmagicdesign.com/support/download/cc533de875ed48219f3095a72a0b75b6/Windows](url)

you can also try your hand at making your own 3Dlut

Link: [https://cameramanben.github.io/LUTCalc/LUTCalc/index.html](url)

**Comment by ABDOELSHEMY** [comment]
much thanks for this great explanation and fast reply @Revan654, i can close this Question now
