### ISSUE TITLE
Check for updates showing error!

### ISSUE THREAD

**Issue by Cyberavater** [Revan654/staxrip#35]
**Describe the bug or Issue**

The system cannot find the file specified

File: D:\Portable

Arguments: Software\StaxRip\Update.bat

**Step To Reproduce the Problem**

1. Go to 'Advanced'
2. Click on 'Check for update'

**Screenshots**
https://imgur.com/a/02b4ijG

**Desktop (please complete the following information):**
 - OS: [Windows 10 Build 1803]
 - Version [2.0]

**Additional context**
I updated to latest 2.0 but I still get this error

**Comment by Revan654** [comment]
It keeps running into TLS issue & it seems you might have PowerShell security in locked stage preventing from certain functions to execute. 

I'm going to Re-Write the Script in Python to stop all this stupid TLS, Power Shell Script was done to make things easier on the user but it seems the script breaks ever few weeks due to HTML Protocols.

This way I can also use much higher level functions and I don't have to deal with PowerShell dumb coding.
