### ISSUE TITLE
[SU] Qaac has been updated to 2.67

### ISSUE THREAD

**Issue by TheMaskedOnion** [Revan654/staxrip#5]
https://sites.google.com/site/qaacpage/cabinet

**Comment by Revan654** [comment]
You can update it manually without the need being recompiled. Only changes I see is the how iPod (5th Gen) get's encoded and nothing major.

it also requires QTfiles64 to work, Which is not included due to copyright reasons. You can gain them via Quicktime Player.

Linkto compiled version & Source Code: https://github.com/nu774/qaac
