### ISSUE TITLE
XAA + QTGMC = Crash

### ISSUE THREAD

**Issue by imPRAGMA** [Revan654/staxrip#59]
**Describe the bug or Issue**
If you add the AVS Filters QTGMC and XAA together, StaxRip will forever go unresponding and eventually crash.

**Step To Reproduce the Problem**

0. Load file
1. Add Field -> QTGMC (Placebo -> Progressive Full Repair)
2. Add Line -> XAA
It will not respond forever and eventually crash.

**Screenshots**
[Freeze](https://i.imgur.com/bOUWIFo.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 1803
- Version 1.9 & 2.0
- FrameServer Being Used Avisynth
- Version of External Application / Filter Being Used Not Sure
- List of Filters Being Used QTGMC and XAA

**Additional context**
It seems to only occur with the specific options I mentioned. Its quite odd.
On 2.0.0.0 XAA doesnt work at all, it says "There is no function named 'TryFTurnRight'."

EDIT: It doesnt occur if you do XAA first but still crashes if you then move XAA after QTGMC

**Comment by Revan654** [comment]
It's likely due to filters & vector files your using which are not supported by your CPU, Most filters are AVX2 enabled by default since some of the updated versions have no AVX version anymore.

- Dither
- eedi2
- eedi3
- FTurn
- MaskTools2
- nnedi3
- nnedi3ocl
- RgTools
- SangNom2
- TCannyMod
- TEMmod
- ResizeX
- edi_rpow2

It doesn't crash, if wrong filters are loaded, it just shoots out the error, the vectors filter is likely your problem.

Plus it doesn't help that AVS+ made FTurn functions useless and I believe it was renamed to LTurn instead of LeftTurn. XAA is pretty much dead. Not sure if I can get it to run in AVS+ anymore or not.

It was pure luck I had it running in the first place since I had to alter the code, I would suggest using VapourSynth(Your going to see allot more of can't run because x is not support due to vectors or other reasons. Allot of Avs filters are just not updated anymore.). Most of the AA scripts have been ported over to VS Plus some better ones like TAAmbk(not sure if XAA was ported over or not). I've been starting to use VS more, Before I only used I only used AVS. Plus VS has QTGMC as well.

Many of the AVS filters even running have problems, creating issues within the video. SVPFlow is one example I noticed Works perfectly in VS, but AVS version creates artifacts & odd jitters around text.
