### ISSUE TITLE
NVenc not recognizing GTX970

### ISSUE THREAD

**Issue by Jeferson-Emanuel** [Revan654/staxrip#6]
For some reason GTX970 is not being recognize has having support to NVenc. Using driver 385.69.

Version 1.7.0.0 recognizes VGA without issues.

**Comment by Jeferson-Emanuel** [comment]
Updating here. Seems to be an issue with NVenc 4.08. Using NVenc 4.07 works without problems.

**Comment by Revan654** [comment]
topic isn't visible anymore since issue been closed with NEVencC has been closed. There are a bunch of issues with NVencC 4.08+. Not to mention improper documentation.  I can only work with whats provided in the release.

I contacted the developer but never heard back. NEVencC is in limbo right now.

**Comment by Jeferson-Emanuel** [comment]
No problem man. Good to know that the problem was not my system or the software itself.

I will keep the 4.07 version here and replace it when you update your program.

And thanks for keeping this project alive.
