### ISSUE TITLE
FFT3DGPU Crash

### ISSUE THREAD

**Issue by fmohican** [Revan654/staxrip#66]
**Describe the bug or Issue**
FFT3DGPU Crash entire program without any logs, after filtre/load plugin a flash of windows console apper and staxrip get freezed and become unresponsive, then close, without any message

**Screenshots**
A screenshot with staxrip freezed isn't for mutch help right?

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 1803 x64
- Version 2.0.0.2
- FrameServer Being Used Avisynth
- List of Filters Being Used FFVideoSource, FFT3DGPU, TextSubMod

**note**
When you add filter via menu, the question with Enable this feature True/False isn't apper, and after add staxrip return an error if illeage usage of $, the fix is easy, just to on filter and replace `NVPerf=$Select:msg:Do you want to use Nvidia Feature;True;False$` with `NVPref=True`, after hit Ok, the program will try to launch that console and freeze.

**Comment by Revan654** [comment]
StaxRip Builds only go up to 2.0.0.0.

Everything loads just fine at my end. It's likely due to you missing a file or two to run the the filter or your GPU doesn't support it(Not all Nvidia GPU's can use that filter).

NVPref=True, all your doing is removing macro system from the filter nothing more. It also removes the choice to enable it or not.

You may want to ask the dev who took over the project: https://github.com/pinterf/FFT3dGPU/issues

The filter does require a much of C++ runtimes to be installed, along with FFTW files & DirectX runtimes.

You also need the hlsl file.

**Comment by fmohican** [comment]
Thanks...
