### ISSUE TITLE
Fake FPS and video lenght

### ISSUE THREAD

**Issue by zildan** [Revan654/staxrip#83]
Hello,
I have a big problem with a h264 recorded movie.
The problem is generated when the movie is wrong imported in StaxRip.
The encoded movie has a half-shot video with incorrect FPS and the correct length audio.
I use latest StaxRip.
Handbrake can correctly encode the movie.

For testing I attach a part of movie.
Please try encoding the movie, and check fps and second part video.
Video has always half of the total frames of original movie and 1/2 fps.
https://yadi.sk/i/Jk5GQItNTtWGBw

**Comment by Revan654** [comment]
HandBrake only uses one Source FFmpeg and nothing else(With Limitation). Since Handbrake doesn't use any form of Frameserver, Can't really compare the two.

That's an issue with the source filter your using, I have no control over those filters. Some haven't been updated in years. I would suggest switching to a different source filter. of Course DGIndexNV will work the best(It's Not a Free Filter). You also have L-Smash or ffms2 being next best for source filters.

**Comment by zildan** [comment]
Thank you ,
With Direct Show Source or DSS2 everything is fine.

I have AMD Ryzen 7 2700U with AMD Radeon(TM) RX Vega 10 Graphics,
I use VCEEncC (x64) 4.02.

![image](https://user-images.githubusercontent.com/4396001/53631175-a06fab80-3c1a-11e9-8191-45ccb9efe874.png)

**Comment by Revan654** [comment]
> 
> 
> Thank you ,
> With Direct Show Source or DSS2 everything is fine.
> 
> I have AMD Ryzen 7 2700U with AMD Radeon(TM) RX Vega 10 Graphics,
> I use VCEEncC (x64) 4.02.
> 
> ![image](https://user-images.githubusercontent.com/4396001/53631175-a06fab80-3c1a-11e9-8191-45ccb9efe874.png)

VCEEnc hasn't been updated in years, There been some small name changes in the code but the core SDK is unchanged since 2016. It's very likely some of the issues is result of that. x265 is still the better road to take since it produces better picture quality.
