### ISSUE TITLE
Staxrip.2.0.0.0.x64 version issues.

### ISSUE THREAD

**Issue by pwacooijmans** [Revan654/staxrip#86]
I think someone forgot to press f12 for all versions in the manage apps section with this version of staxrip.
I choose the second option for storing my settings which is directly inside the staxrip directory in the directory settings. NEARLY no versions were detected correctly.

Many Thanks for Fixing this issue.

Kind Regards,

Pieter Cooijmans

**Comment by Revan654** [comment]
Use the Pipeline build(Check Front Page), One posted here is outdated.

**Comment by iAM261917** [comment]
> Use the Pipeline build(Check Front Page), One posted here is outdated.
> 
> That was all due to dotnet bug. Since it was fine at my end, once it hit the user PC it came up as outdated.

I think that's probably because you forgot to add file modification time when compressing files. When users decompress files using WinRAR, file modification time will be set to the current system time, but other compression software may set all files to 1985, which leads StaxRip to think that all components are outdated.
![imt](https://user-images.githubusercontent.com/42721712/54718458-8714ac00-4b95-11e9-9def-a0555f172429.png)
