### ISSUE TITLE
d2vsource

### ISSUE THREAD

**Issue by Mike-83** [Revan654/staxrip#93]
Hello!
Found bug.
D2V parser and decoder for VapourSynth (d2vsource)  that in package-  old version (v.1.0)
Bug - Incorrect duration when loading Mpeg-2 source
With new version 1.1 d2vsource it`s allright.

Please replace with the new version in the installer

**Comment by Revan654** [comment]
You can already update it your self. Most use NV version now of days. The old or slightly newer version should work the same, shouldn't have a issue with reading the mpeg-2 length in the file unless the mpeg-2 header is corrupted.

or MediaInfo is reporting bad data (Which can be likely, Since it has happened before).

**Comment by Mike-83** [comment]
In new version bug fixed.
And only new version allowed to successfully encoded.
Maybe it will be useful to someone else.
Anyway, thanks for continuing work !

**Comment by Revan654** [comment]
> 
> 
> In new version bug fixed.
> And only new version allowed to successfully encoded.
> Maybe it will be useful to someone else.
> Anyway, thanks for continuing work !

Could be your source file. Since I have zero reports on any issues of d2v creating issues, dunno.
